Issue 2
Students-of-the-city-of-Kostroma/TPRO pull request #3
Opened 2020-10-15 19:15 UTC by Kruuliter

2020-10-23 05:40 UTC, YuriSilenok requested changes
У вас не получился КДА.

2020-10-23 05:40 UTC, YuriSilenok commented on logic/event.py
> +        if (re.match(final_text['alien_element'],text_file[line])==True):
Упростить условия `if (re.match(final_text['alien_element'],text_file[line])==True):` 
на `if re.match(final_text['alien_element'], text_file[line]):` соблюдайте отступы при перечислении атрибутов в методы.

2020-10-23 05:40 UTC, YuriSilenok commented on logic/event.py
> +                        if(re.match(final_text['title_third_level'],text_file[line])==True):
Вы ожидаете что к одной строке сработают все три правила?

2020-10-23 14:30 UTC, Kruuliter commented on logic/event.py
> +                        if(re.match(final_text['title_third_level'],text_file[line])==True):
Это сделано для более точного определения заглавий, т.к. в методических рекомендациях в заглавиях используется один и тот же символ, разница лишь в количестве, а заглавие первого уровня следуя методической рекомендации попадается в первой строке. Что будет, если заглавие первого уровня попадется не только в первой строке, но и во второй, получается это ошибка в составлении отчета. Такой логике я следовал и получились эти условия.

2020-11-01 10:30 UTC, YuriSilenok commented
Я залью изменения, посмотрим как это будет работать

2020-11-01 10:30 UTC, merged